name: Build, Deploy, and Test All Examples

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente"
        required: true
        default: "prod"
        type: choice
        options: [dev, staging, prod]
      skip_cache:
        description: "Forçar rebuild total"
        default: true
        type: boolean
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  NODE_VERSION: "24"
  ZE_API_GATE: ${{ github.event.inputs.environment == 'dev' && 'https://zeapi.zephyrcloudapp.dev' || github.event.inputs.environment == 'staging' && 'https://zeapi.zephyrcloudapp.xyz' || 'https://zeapi.zephyrcloud.app' }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: {version: 10.6.3}
      - id: set-matrix
        # Aqui definimos quais pastas serão testadas em paralelo
        run: echo "matrix=[\"vanilla\", \"nx/examples\", \"turborepo/examples\"]" >> $GITHUB_OUTPUT

  build-test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node & PNPM Cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm' 

      - name: Install Project Deps
        run: |
          cd ${{ matrix.folder }}
          pnpm install --prefer-offline

      - name: Build & Clean Zephyr
        run: |
          rm -rf $HOME/.zephyr && mkdir -p $HOME/.zephyr
          pnpm build
        env:
          ZE_SECRET_TOKEN: ${{ secrets[format('ZE_SECRET_TOKEN_{0}', github.event.inputs.environment || 'PROD')] }}
          ZE_API_GATE: ${{ env.ZE_API_GATE }}

      - name: Playwright Validation
        run: |
          npx playwright install chromium --with-deps
          pnpm test
